experiment_name: Experiment3
model_type: all
data_path: data/sample_train_100.csv
target_column: tag
similarity_threshold: 0.05

important_features:
  - POSIX_SEQ_WRITES
  - POSIX_SIZE_READ_1K_10K
  - POSIX_SIZE_READ_0_100
  - POSIX_SIZE_WRITE_100K_1M
  - POSIX_MEM_NOT_ALIGNED
  - POSIX_FILE_NOT_ALIGNED
  - POSIX_SEEKS
  - POSIX_OPENS

hyperparams:
  hidden_dim: 64
  num_layers: 2
  dropout: 0.1
  batch_size: 32
  epochs: 100
  lr: 0.001
  weight_decay: 0.0001
  patience: 10
  seed: 42
